### ISSUE TITLE
facebook has a golang ent project

### ISSUE THREAD

**Issue by dryaf** [google/ent#1]
https://github.com/ent/ent
https://entgo.io/

maybe a different name would be better

**Comment by tiziano88** [comment]
Thanks, that's quite awkward indeed, I didn't realise it, I may think of a different name, but hopefully it should be obvious they are unrelated projects.

**Comment by tiziano88** [comment]
I don't think I'll rename this project after all, there is not much overlap between the two, their purposes are different, and even though the names are spelled equally, their etymology is actually quite distinct, so I'm not worried that anyone would actually confuse them.
